http:
  routers:
    cpphse-router:
      rule: "Host(`cpp-hse.org`)"
      entryPoints:
      - websecure
      service: cpphse
      middlewares:
      - gzip-compress

tcp:
  routers:
    entryPoints:
      - tcp9k
    service: crashme


  middlewares:
    gzip-compress:
      compress: {}

  services:
    cpphse:
      loadBalancer:
        servers:
          - url: "http://localhost:18080/" 

    crashme:
      loadBalancer:
        servers:
          - address: "localhost:18228"
