version: "3"

services:
  notmanytask:
    image: bigredeye/notmanytask:latest
    ports:
      - 18080:18080
    volumes:
      - ./notmanytask/config.yml:/etc/notmanytask/config.yml
      - ./notmanytask/logs:/var/log/notmanytask
    restart: unless-stopped

  crashme:
    image: bigredeye/notmanytask:crashme
    ports:
      - 9090:9090
    volumes:
      - ./crashme/config.yml:/etc/crashme/config.yml
      - ./crashme/submits:/var/run/crashme/submits
    environment:
      CRASHME_URL: https://cpp-hse.org/api/flag
      CRASHME_TOKEN: TOKEN
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: {POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: unless-stopped

  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/configs:/etc/traefik/configs
      - ./traefik/logs:/var/log/traefik/logs
      - traefik-acme:/acme
    network_mode: host
    restart: unless-stopped

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 5
    restart: unless-stopped

volumes:
  traefik-acme:
