version: "3"

services:
  notmanytask:
    image: bigredeye/notmanytask:latest
    ports:
      - 18080:18080
    volumes:
      - ./notmanytask/config.yml:/etc/notmanytask/config.yml
    restart: unless-stopped

  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/configs:/etc/traefik/configs
      - ./traefik/logs:/var/log/traefik/logs
      - traefik-acme:/acme
    network_mode: host

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 5

volumes:
  traefik-acme:
